#!/usr/bin/env python3
"""Generate the benchmark corpus.

The corpus is *generated*, not committed: `bench/corpus/1mb.md` is a megabyte of
synthetic markdown, and a megabyte of generated text in git is noise that every
clone pays for forever. This script is the committed artifact instead, so the
numbers in `research.md` stay reproducible.

The construct mix matches the corpus the research measurements were taken
against (research §1): roughly 15% of bytes in fenced code, task lists, tables,
headings, and prose, so `syntect` sees a realistic share of the document.

    python3 scripts/gen-corpus.py            # write bench/corpus/*.md
    python3 scripts/gen-corpus.py --list     # show what would be written
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

# (name, target bytes) — the four sizes research measured.
SIZES = [
    ("8kb.md", 8 * 1024),
    ("256kb.md", 256 * 1024),
    ("1mb.md", 1024 * 1024),
]

WORDS = (
    "document render block parse highlight cache toggle checkbox byte range "
    "offset heading paragraph fence table quote anchor index milestone "
    "measurement threshold viewport layout paint pipeline"
).split()

CODE = {
    "rust": 'fn block_{n}(input: &str) -> usize {{\n    let mut total = 0;\n'
            '    for (index, line) in input.lines().enumerate() {{\n'
            '        total += index * line.len();\n    }}\n    total\n}}\n',
    "python": 'def block_{n}(rows):\n    total = 0\n    for index, row in enumerate(rows):\n'
              '        total += index * len(row)\n    return total\n',
    "json": '{{"block": {n}, "kind": "sample", "values": [1, 2, 3], "ok": true}}\n',
    "bash": 'for f in *.md; do\n  mark render "$f" --plain > "out/{n}-$f.txt"\ndone\n',
}


def paragraph(rng: random.Random, n: int) -> str:
    words = [rng.choice(WORDS) for _ in range(rng.randint(30, 70))]
    words[0] = words[0].capitalize()
    return f"Paragraph {n}. " + " ".join(words) + ".\n\n"


def code_block(rng: random.Random, n: int) -> str:
    language = rng.choice(list(CODE))
    return f"```{language}\n" + CODE[language].format(n=n) + "```\n\n"


def task_list(rng: random.Random, n: int) -> str:
    lines = []
    for i in range(rng.randint(2, 5)):
        mark = "x" if rng.random() < 0.4 else " "
        lines.append(f"- [{mark}] task {n}.{i} {rng.choice(WORDS)}")
    lines.append(f"1. [ ] ordered task {n}")
    return "\n".join(lines) + "\n\n"


def table(_rng: random.Random, n: int) -> str:
    return (
        f"| block {n} | value | note |\n|---|---:|---|\n"
        "| alpha | 1 | first |\n| beta | 22 | second |\n| gamma | 333 | third |\n\n"
    )


def quote(rng: random.Random, n: int) -> str:
    return f"> Note {n}: {' '.join(rng.choice(WORDS) for _ in range(12))}.\n\n"


def generate(target_bytes: int, seed: int = 20260824) -> str:
    """Deterministic for a given size, so two runs produce identical files."""
    rng = random.Random(seed)
    out = ["# Benchmark corpus\n\n",
           "Generated by `scripts/gen-corpus.py`. Do not edit; do not commit.\n\n"]
    size = sum(len(part) for part in out)
    n = 0

    # Weights chosen so code lands at ~15% of bytes, matching research 2.10.
    generators = [paragraph] * 5 + [code_block] * 3 + [task_list, table, quote]

    while size < target_bytes:
        n += 1
        if n % 12 == 1:
            part = f"## Section {n // 12 + 1}\n\n"
        elif n % 12 == 7:
            part = f"### Subsection {n}\n\n"
        else:
            part = rng.choice(generators)(rng, n)
        out.append(part)
        size += len(part)
    return "".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "bench/corpus",
        help="output directory (default: bench/corpus)",
    )
    parser.add_argument("--list", action="store_true", help="only report what would be written")
    args = parser.parse_args()

    for name, target in SIZES:
        path = args.out / name
        if args.list:
            print(f"{path}  ~{target} bytes")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        body = generate(target)
        path.write_text(body, encoding="utf-8")
        print(f"{path}  {len(body)} bytes")


if __name__ == "__main__":
    main()
